# Generated by Django 3.0.6 on 2020-05-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('cover', models.ImageField(default='default.jpg', upload_to='covers')),
                ('song', models.FileField(default='default.mp3', upload_to='songs')),
            ],
        ),
    ]
