# Generated by Django 3.0.6 on 2020-05-30 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_song_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumentals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('cover', models.ImageField(default='default2.jpg', upload_to='covers')),
                ('song', models.FileField(default='default2.mp3', upload_to='songs')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
